jms_serializer:
    metadata:
        auto_detection: false
        directories:
            products_catalog:
                namespace_prefix: "ProductsCatalog"
                path: "%kernel.project_dir%/config/serializer"
