jms_serializer:
    metadata:
        auto_detection: false
        directories:
            app:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/config/serializer"
